services:
  docling-api:
    build: .
    env_file:
      - env.local
    ports:
      - "8000:8000"

    volumes:
      - workspace_data:/home/appuser/.EasyOCR
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  workspace_data:
