services:
  docling-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OMP_NUM_THREADS=${OMP_NUM_THREADS:-4}  # Cores per process (default: 4 for local)
      - UVICORN_WORKERS=${UVICORN_WORKERS:-4}  # Number of worker processes (default: 4 for API handling)
      - UPSTASH_REDIS_URL=${UPSTASH_REDIS_URL}
    volumes:
      - workspace_data:/home/appuser/.EasyOCR
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  workspace_data:
